version: "3.9"

services:
  snippetbox-mysql:
    image: mysql:5.7
    restart: always
    container_name: snippetbox-mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: snippetbox
volumes:
  db_data: